# Jekyll configuration for Open SDG platform
#
# You will need to change all of the capitalized variables below according
# to your Github setup. For example, if your site and data repositories are:
# -- https://github.com/my-awesome-github-org/my-awesome-site-repo
# -- https://github.com/my-awesome-github-org/my-awesome-data-repo
# Then you would want to make these replacements throughout this file:
# -- replace "my-github-org" with "my-awesome-github-org"
# -- replace "open-sdg-site-starter" with "my-awesome-site-repo"
# -- replace "open-sdg-data-starter" with "my-awesome-data-repo"

# NOTE: This "production" version only contains differences from _config.yml.
baseurl: ""
environment: production
remote_data_prefix: "https://armstat.github.io/sdg-data-armenia/prod"
analytics:
  ga_prod: 'UA-17758567-2'
