accessible_charts: true
accessible_tabs: true
analytics:
  ua: ''
  gtag: ''
  gtm: ''
  ga_prod: ''
breadcrumbs:
  goal:
    - path: /
      label: general.home
    - path: /goals
      label: general.goals
  indicator:
    - path: /
      label: general.home
    - path: /goals
      label: general.goals
  post:
    - path: /
      label: general.home
    - path: /news
      label: menu.updates
contrast_type: single
cookie_consent_form:
  enabled: false
country:
  name: custom.armenia
  adjective: custom.armenian
create_goals:
  layout: goal-with-progress
  previous_next_links: false
  goals: []
create_indicators:
  layout: indicator
  previous_next_links: false
create_pages:
  - filename: ''
    folder: /
    layout: frontpage-alt
    title: ''
  - filename: ''
    folder: /goals
    layout: goals
    title: ''
  - filename: ''
    folder: /reporting-status
    layout: reportingstatus
    title: ''
  - filename: indicators.json
    folder: /
    layout: indicator-json
    title: ''
  - filename: ''
    folder: /search
    layout: search
    title: ''
custom_css: []
custom_js:
  - /assets/js/custom.js
data_edit_url: data
data_fields:
  units: ''
  series: ''
date_formats: []
disclaimer:
  phase: ''
  message: ''
email_contacts:
  questions: ''
  suggestions: ''
  functional: ''
environment: staging
favicons: favicon.io
footer_language_toggle: none
footer_menu:
  - path: /faq
    translation_key: menu.faq
  - path: /about/cookies-and-privacy/
    translation_key: menu.cookies
frontpage_cards:
  - title: frontpage.download_all
    content: ''
    include: components/download-all-data.html
    button_label: ''
    button_link: ''
    rule_color: ''
frontpage_goals_grid:
  title: custom.frontpage_grid_title
  description: goal.description
frontpage_heading: ''
frontpage_instructions: ''
frontpage_introduction_banner:
  title: frontpage.intro_title
  description: frontpage.intro_body
goal_image_base: 'https://open-sdg.org/sdg-translations/assets/img/goals'
goal_image_extension: ''
goals_page:
  title: general.goals
  description: goal.description
graph_color_headline: '#004466'
graph_color_headline_high_contrast: '#55a6e5'
graph_color_set: accessible
graph_color_list: []
graph_color_number: 0
graph_title_from_series: false
header:
  include: header-menu-left-aligned.html
header_language_toggle: dropdown
hide_empty_metadata: true
hide_single_series: true
hide_single_unit: true
indicator_config_form:
  enabled: true
  dropdowns: []
  repository_link: /tree/develop/indicator-config
  translation_link: ''
indicator_data_form:
  enabled: true
  repository_link: /tree/develop/data
indicator_metadata_form:
  enabled: true
  dropdowns: []
  repository_link: /tree/develop/meta
  translation_link: ''
  language: ''
  scopes:
    - national
    - global
  exclude_fields: []
  translated: false
indicator_tabs:
  tab_1: ''
  tab_2: ''
  tab_3: ''
  tab_4: ''
languages:
  - en
  - hy
  - ru
languages_public:
  - language: hy
    language_public: am
logos: []
map_layers: []
map_options:
  minZoom: 5
  maxZoom: 10
  tileURL: ''
  tileOptions:
    id: ''
    accessToken: ''
    attribution: ''
  colorRange: chroma.brewer.BuGn
  noValueColor: '#f0f0f0'
  styleNormal:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#888888'
    dashArray: ''
  styleHighlighted:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#111111'
    dashArray: ''
  styleStatic:
    weight: 2
    opacity: 1
    fillOpacity: 0
    color: '#172d44'
    dashArray: '5,5'
menu:
  - path: /reporting-status
    translation_key: menu.reporting_status
    dropdown: []
  - path: /about
    translation_key: menu.about
    dropdown: []
  - path: /guidance
    translation_key: menu.guidance
    dropdown: []
  - path: /faq
    translation_key: menu.faq
    dropdown: []
metadata_edit_url: metadata
metadata_tabs: []
news:
  category_links: false
non_global_metadata: indicator.national_metadata
progress_status:
  status_heading: ''
  status_types: []
remote_data_prefix: 'https://armstat.github.io/sdg-data-armenia/staging'
reporting_status:
  title: status.reporting_status
  description: status.description
  disaggregation_tabs: false
  status_types:
    - value: complete
      label: status.reported_online
      hide_on_goal_pages: false
    - value: inprogress
      label: status.statistics_in_progress
      hide_on_goal_pages: false
    - value: notstarted
      label: status.exploring_data_sources
      hide_on_goal_pages: false
repository_url_data: 'https://github.com/armstat/sdg-data-armenia'
repository_url_site: 'https://github.com/armstat/sdg-site-armenia'
search_index_boost: []
search_index_extra_fields: []
series_toggle: true
site_config_form:
  enabled: true
  dropdowns: []
  repository_link: /tree/develop/_data
  translation_link: ''
validate_indicator_config: false
validate_site_config: false
x_axis_label: ''